name: CI
on: [push]

jobs:
  build-library:
    runs-on: ubuntu-latest
    name: build-library
    # Markdown validation tests
    steps:
      - uses: actions/checkout@v1
      - uses: teddywilson/shisito@v1.0.0