name: CI
on: [push]

jobs:
  markdown-validation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: teddywilson/shisito-markdown-validation@v1.1.10
  deploy:
    runs-on: ubuntu-latest
    needs: markdown-validation-tests
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - name: Install Gatsby CLI
      run: sudo npm install -g gatsby-cli
      id: install-gatsby
    - name: Run deployment script
      run: /home/runner/work/clothesline-recordings/clothesline-recordings/deploy
      id: deployment-script
